# Generated by Django 2.0.13 on 2020-07-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(default='', max_length=20)),
                ('time_day', models.CharField(default='', max_length=30)),
                ('time_sub', models.CharField(default='', max_length=30)),
                ('sub_name', models.CharField(default='', max_length=200)),
                ('sub_num', models.IntegerField(default=0)),
            ],
        ),
    ]
