# Generated by Django 2.0.13 on 2020-07-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200723_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sub_name',
            field=models.CharField(default='0&0&0&0&0&0&0', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='time_day',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='time_sub',
            field=models.CharField(default='0&0&0&0&0&0&0', max_length=30),
        ),
    ]
