# Generated by Django 2.0.13 on 2020-07-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200723_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='idCode',
            field=models.IntegerField(default=0),
        ),
    ]
