# Generated by Django 2.0.13 on 2020-07-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_idcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='todo_name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='user',
            name='todo_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='sub_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='time_day',
            field=models.CharField(default='0-0-0-0-0-0-0', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='time_sub',
            field=models.CharField(default='0-0-0-0-0-0-0', max_length=30),
        ),
    ]
