# Generated by Django 2.0.13 on 2020-07-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200725_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='todo_name',
            field=models.CharField(default='0:0', max_length=300),
        ),
        migrations.AlterField(
            model_name='user',
            name='todo_num',
            field=models.IntegerField(default=1),
        ),
    ]
