# Generated by Django 2.0.13 on 2020-07-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200726_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time_sub',
            field=models.CharField(default='0-0-0-0-0-0-0-0-0-0', max_length=30),
        ),
    ]
